apiVersion: v1
kind: Service
metadata:
  name: ex-api
  labels:
    app: ex-api
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      protocol: "TCP"
  selector:
    app: ex-api
